recycleEnderDragonEgg: true
saturdayFly: true
saturdayNightVision:
  enable: true
  mvp: nightvision.use
  toggleAction: "夜视模式模式已<{status}>"
iaRecipe:
  debug: true
  coinName: "token_1"
  recipeCost:
    # 辉钻石锭
    "itemsadder:cobaltite_block_0": 10
    # 钴华石锭
    "zzzfake_itemsadder:cobaltite_block_0": 10
  iaRecipeCostLack:
    - "mini: &c&l！&4合成 {itemName} 失败，需要 {cost}，当前拥有: {money}"
  iaRecipeSuccess:
    - "mini: &c&l！&4合成 {itemName} 成功，消耗金钱 {cost}，当前拥有: {money}"
chunkLogger:
  debug: true
checkPlayerInventory:
  log: "玩家: {player} 持有物品({status}) {itemText}，超出限制"
  info: "&c玩家: {player} 持有物品({status}) {itemText}，超出限制"
  item:
    - "itemsadder:xxx|10"
#iaItemAutoUpdate:
#  info:
#    - "mini: 物品 {itemName} 已经被更新"
#  item:
#    - "itemsadder:xxx"
placeholder:
  test:
    target: '%player_name%'
    change:
      MokierTea: "技术"
      Mainyf: "插件"
      not: "没有"
    other: "%player_name%"