debug: false
# 重置岛屿冷却时间，单位为天
resetCooldown: 1
coreId: "plot:plot_main"
islandHelperMaxCount: 7
backLobby:
  - "console: cmi server spawn {player}"
schematics:
  hupo:
    iaIcons: '0:offset_-174::view_plot_types_0:'
    ui:
      name: " &c&l> &3湖泊"
      lore: [ ]
    core: -75,-104,-98
  shamo:
    iaIcons: '1:offset_-5::view_plot_types_1:'
    ui:
      name: " &c&l> &3沙漠"
      lore: [ ]
    core: -62,-67,-105
  xueshan:
    iaIcons: '2:offset_-5::view_plot_types_2:'
    ui:
      name: " &c&l> &3雪山"
      lore: [ ]
    core: -101,-57,-172
  pingyuan:
    iaIcons: '0:offset_-174::view_plot_types_3:'
    ui:
      name: " &c&l> &3平原"
      lore: [ ]
    core: -102,-74,-111
  gaoshan:
    iaIcons: '1:offset_-5::view_plot_types_4:'
    ui:
      name: " &c&l> &3高山"
      lore: [ ]
    core: -79,-91,-168
moveCoreAction:
  - "title: ,&3使用&b左键确认&3核心水晶位置,0,20,10"
  - "actionbar: &6&l使用 &e&lShift+左键 &6&l取消移动,&c◆"