coreId: "itemsadder:amethyst_block"
backLobby:
  - "message: 返回大厅"
schematics:
  gaoshan:
    ui:
      name: "高山"
      lore:
        - "高山地形"
    core: -96,-175,-84
  hupo:
    ui:
      name: "湖泊"
      lore:
        - "湖泊地形"
    core: 20,20,20
  pingyuan:
    ui:
      name: "平原"
      lore:
        - "平原地形"
    core: 20,20,20
  shamo:
    ui:
      name: "沙漠"
      lore:
        - "沙漠地形"
    core: 20,20,20
  xueshan:
    ui:
      name: "雪山"
      lore:
        - "雪山地形"
    core: 20,20,20