database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "123456"
  databaseName: "minecraft"
initMenuTipsName: "当前选择的赋予的附魔是 {skill}"
initMenuTipsLore:
  - "当前选择的赋予的附魔是 {skill}"
upgradeMenuTipsName: "当前选择进阶的附魔是 {skill}"
upgradeMenuTipsLore:
  - "当前选择进阶的附魔是 {skill}"
exp:
  # 每两级所需经验增加
  level: '100*(level/2)'
  # 能获取经验值的实体
  # 支持：MM怪物、 原版怪物
  # MM怪物ID 或 原版怪物类型 或 other:经验值
  entitys:
    - 'other:2'
    - '怨灵1:80'
    - 'Zombie:100'
  # 能获取经验值的方块
  # 方块类型:经验值
  blocks:
    - 'other:2'
    - 'enchant_ore_high:192'
    - 'enchant_ore:64'
    - 'emerald_ore:64'
    - 'diamond_ore:64'
    - 'gold_ore:36'
    - 'iron_ore:32'
    - 'coal_ore:24'
    - 'lapis_ore:24'
    - 'redstone_ore:24'
    - 'nether_gold_ore:32'
    - 'nether_quartz_ore:24'
    - 'stone:1'
    - 'cobblestone:1'
    - 'granite:1'
    - 'diorite:1'
    - 'andesite:1'
    - 'grass_block:1'
    - 'dirt:1'
    - 'coarse_dirt:1'
    - 'podzol:1'
    - 'terracotta:1'
    - 'white_terracotta:1'
    - 'orange_terracotta:1'
    - 'magenta_terracotta:1'
    - 'light_blue_terracotta:1'
    - 'yellow_terracotta:1'
    - 'lime_terracotta:1'
    - 'pink_terracotta:1'
    - 'gray_terracotta:1'
    - 'light_gray_terracotta:1'
    - 'cyan_terracotta:1'
    - 'purple_terracotta:1'
    - 'blue_terracotta:1'
    - 'brown_terracotta:1'
    - 'green_terracotta:1'
    - 'red_terracotta:1'
    - 'black_terracotta:1'

itemaddersNamespace: "itemskills"
equipments:
  # 对应ItemAdders的物品ID
  expand:
    # 之后开启时起效果，用于出BUG时临时关闭
    enabled: true
    # 进阶装备的名称
    name: '凿石'
    # 装备lore介绍
    # {stage}  阶段级别  I、II、III
    # {exp_progress}  经验进度条
    description:
      - '&r'
      - '&f&l凿石 {stage}'
      - ' &7等级: &f&lLv.{level}  &8&l[{exp_progress}&8&l] '
      - '&r'
    # 允许一二阶段起效果的方块
    # 支持 ItemAdders 和原版方块
    allowBlocks:
      - sand
      - sandstone
      - stone
      - cobblestone
      - granite
      - diorite
      - andesite
      - grass_block
      - dirt
      - coarse_dirt
      - podzol
      - terracotta
      - white_terracotta
      - orange_terracotta
      - magenta_terracotta
      - light_blue_terracotta
      - yellow_terracotta
      - lime_terracotta
      - pink_terracotta
      - gray_terracotta
      - light_gray_terracotta
      - cyan_terracotta
      - purple_terracotta
      - blue_terracotta
      - brown_terracotta
      - green_terracotta
      - red_terracotta
      - black_terracotta
    skin: "expandDefaultSkinA"
    upgradeMaterials:
      - "eqMaterial1:32,eqMaterial2:32,eqMaterial3:32,eqMaterial4:32,eqMaterial5:32"
      - "eqMaterial1:64,eqMaterial2:64,eqMaterial3:64,eqMaterial4:64,eqMaterial5:64"
      - "eqMaterial1:128,eqMaterial2:128,eqMaterial3:128,eqMaterial4:128,eqMaterial5:128"

  luck:
    enabled: true
    name: '福临'
    max: 25
    description:
      - '&r'
      - '&f&l福临 {stage}'
      - ' &7等级: &f&lLv.{level}  &8&l[{exp_progress}&8&l] '
      - '&r'
    # 支持掉落翻倍的方块
    # 支持 ItemAdders 和原版方块
    # 玩家放置的不起效果
    allowBlocks:
      - enchant_ore_high
      - enchant_ore
      - emerald_ore
      - diamond_ore
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - redstone_ore
      - nether_gold_ore
      - nether_quartz_ore
    skin: "luckDefaultSkinA"
    upgradeMaterials:
      - "eqMaterial1:32,eqMaterial2:32,eqMaterial3:32,eqMaterial4:32,eqMaterial5:32"
      - "eqMaterial1:64,eqMaterial2:64,eqMaterial3:64,eqMaterial4:64,eqMaterial5:64"
      - "eqMaterial1:128,eqMaterial2:128,eqMaterial3:128,eqMaterial4:128,eqMaterial5:128"

  sharp:
    enabled: true
    name: '陵劲'
    description:
      - '&r'
      - '&f&l陵劲 {stage}'
      - ' &7等级: &f&lLv.{level}  &8&l[{exp_progress}&8&l] '
      - '&r'
    # 每阶段的伤害提升百分比
    damageForm: '50,100,200'
    skin: "sharpDefaultSkinA"
    upgradeMaterials:
      - "eqMaterial1:32,eqMaterial2:32,eqMaterial3:32,eqMaterial4:32,eqMaterial5:32"
      - "eqMaterial1:64,eqMaterial2:64,eqMaterial3:64,eqMaterial4:64,eqMaterial5:64"
      - "eqMaterial1:128,eqMaterial2:128,eqMaterial3:128,eqMaterial4:128,eqMaterial5:128"
  power:
    enabled: true
    name: '精准'
    speed: 2
    description:
      - '&r'
      - '&f&l精准 {stage}'
      - ' &7等级: &f&lLv.{level}  &8&l[{exp_progress}&8&l] '
      - '&r'
    # 每阶段的伤害提升百分比
    damageForm: '50,100,200'
    skin: "powerDefaultSkinA"
    upgradeMaterials:
      - "eqMaterial1:32,eqMaterial2:32,eqMaterial3:32,eqMaterial4:32,eqMaterial5:32"
      - "eqMaterial1:64,eqMaterial2:64,eqMaterial3:64,eqMaterial4:64,eqMaterial5:64"
      - "eqMaterial1:128,eqMaterial2:128,eqMaterial3:128,eqMaterial4:128,eqMaterial5:128"