# 每两级所需经验增加
level: '100*(level/2)'
enchantIntensifyMaterials:
  - 'itemenchants:eqMaterial1|16'
  - 'itemenchants:eqMaterial2|16'
  - 'itemenchants:eqMaterial3|16'
  - 'itemenchants:eqMaterial4|16'
  - 'itemenchants:eqMaterial5|16'