togethers:
  newbie:
    # 持续多久(tick)
    duration: 600
    # 需要发送多少字符的信息才能领取
    msgLength: 6
    # 是否必须中文
    chinese: true
    # 开启时发送的信息
    startActions:
      - "message: 欢迎━(*｀∀´*)ノ亻!玩家{player}加入服务器"
    # 领取的奖励
    reward:
      - 'title: ,&f赠送你 200 发展资金哦,5,20,5'
      - 'console: money give {player} 200'