debug: false
# 出售商店
buyShop:
  DIAMOND: "82,8000"
  RAW_GOLD: "24,8000"
  RAW_IRON: "20,8000"
  RAW_COPPER: "2.5,8000"
  AMETHYST_SHARD: "58,8000"
  LAPIS_LAZULI: "2.5,8000"
  REDSTONE: "2.5,8000"
  COAL: "2.5,8000"
  QUARTZ: "2.5,8000"
  BAMBOO: "0.8,5000"
  SUGAR_CANE: "1.5,5000"
  MELON_SLICE: "0.25,5000"
  PUMPKIN: "1.5,5000"
  CACTUS: "1,5000"
  SWEET_BERRIES: "1.5,5000"
  GLOW_BERRIES: "3,5000"