debug: false
addPermission: "shopmanager.add"
# 出售商店
buyShop:
  DIAMOND: "82,8000"
  RAW_GOLD: "24,8000"
  RAW_IRON: "20,8000"
  RAW_COPPER: "2.5,8000"
  AMETHYST_SHARD: "58,8000"
  LAPIS_LAZULI: "2.5,8000"
  REDSTONE: "2.5,8000"
  COAL: "2.5,8000"
  QUARTZ: "2.5,8000"
  BAMBOO: "0.8,5000"
  SUGAR_CANE: "1.5,5000"
  MELON_SLICE: "0.25,5000"
  PUMPKIN: "1.5,5000"
  CACTUS: "1,5000"
  SWEET_BERRIES: "1.5,5000"
  GLOW_BERRIES: "3,5000"
shopPrice:
  # 最低,最高    如果为 ~,100 则无最低价    为 1,~ 则无最高价
  DIAMOND: "0.5,1000"
  "itemsadder:stone": "0.5,1000"
shopTax:
  DIAMOND: 0.6