noUsageCommand:
  - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
  - "message: &c&l！&4不是发送指令哦，请直接发送密码。"
register:
  stage1:
    period: 20
    actions:
      - "title: &7[&e注册&7],&3请在聊天栏发送你的密码,0,30,10"
      - 'console: cmi bossbarmsg {player} &7&l[&c注意&7&l] &7请确保密码复杂性， 以免出现盗号情况 &7&l[&c注意&7&l] -t:3 -c:WHITE -s:1 -n:join -p:1/1'
      - 'console: cmi effect {player} blindness 20'
      - 'console: cmi effect {player} invisibility 20'
    nextStage:
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
  stage2:
    period: 20
    actions:
      - "title: &7[&e注册&7],&3请在聊天栏再次发送你的密码,0,30,10"
      - 'console: cmi bossbarmsg {player} &7&l[&c注意&7&l] &7请确保密码复杂性， 以免出现盗号情况 &7&l[&c注意&7&l] -t:3 -c:WHITE -s:1 -n:join -p:1/1'
      - 'console: cmi effect {player} blindness 20'
      - 'console: cmi effect {player} invisibility 20'
      - 'console: cmi heal {player}'
    nextStage:
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
    registerNoRepeat:
      - "message: &c&l！&4输入的两次密码不相同，请重新注册。"
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
    registerSuccess:
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
login:
  stage1:
    period: 20
    actions:
      - "title: &7[&e登录&7],&3请在聊天栏发送你的密码,0,30,10"
      - 'console: cmi bossbarmsg {player} &7&l[&c注意&7&l] &7请确保密码复杂性， 以免出现盗号情况 &7&l[&c注意&7&l] -t:3 -c:WHITE -s:1 -n:join -p:1/1'
      - 'console: cmi effect {player} blindness 20'
      - 'console: cmi effect {player} invisibility 20'
    nextStage:
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
    noBindQQNum:
      - "message: &c&l！&4你没有绑定qq，无法找回密码。"
    loginSuccess:
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
    passwordWrong:
      - "message: &c&l！&4密码错误。（错误5次将半小时不能登陆）"
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
    # 密码错误尝试的最长时间，超出这个时间则错误次数重新计算
    passwordAttemptsMaxTime: 6
    # 错误密码的尝试次数
    passwordAttempts: 5
    # 密码错误后不能进入服务器的时间
    passwordWrongBlackListTime: 30
    # 踢出的格式
    blackListKickFormat:
      - "&7你登陆失败过多，请 &f{time} &7后再尝试。"
resourcePack:
  url: "https://mokier-cnc.oss-cn-hangzhou.aliyuncs.com/v0.2.9.zip"
  declined:
    - 'console: cmi warp help {player}'
    - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
    - 'console: cmi effect {player} blindness 1'
  failDownload:
    - "title: ,&e服务器材质下载失败,0,30,10"
    - "message: &c&l！&4服务器材质包下载失败。"
  successLoad: []
teachingMenu:
  cooldown: 250
  row: 6
  background: ':offset_-8::view_login_teaching::offset_-136::view_login_teaching_msg::offset_-115:'
  # 正确选择
  slotA:
    slot: [28,29,30,31,32]
    iaIcons: [
      "0:view_login_teaching_yes:",
      "0:offset_18::view_login_teaching_yes:",
      "0:offset_36::view_login_teaching_yes:",
      "0:offset_54::view_login_teaching_yes:",
      "0:offset_72::view_login_teaching_yes:"
    ]
    actions:
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,1"
      - "console: trmenu open servers {player}"
    playRules:
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,1"
      - "console: trmenu open treaty {player}"
    type: air
    name: ""
  # 错误选择
  slotB:
    slot: "37-43"
    iaIcons: 'xx'
    actions:
      - 'console: cmi warp help1 {player}'
      - "sound: BLOCK_NOTE_BLOCK_BELL,1,0"
      - 'console: cmi effect {player} blindness 1'
    type: RED_STAINED_GLASS_PANE
    name: ""
playRuleNoExpired: []
playRuleSuccess: []